### PR TITLE
Added mbed_lib.json based default constructor

### PR DESCRIPTION
**Pull request by AnttiKauppila**

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
Problem with this pattern is failure to compile on boards which lack the necessary pin names. If you could limit the "D0/D1" to only boards with ARDUINO form factor would be okay. Possible in JSON?

Or maybe the arduino defaults could be put in the C code.

**Comment by kjbracey-arm** [comment]
Basically, I'd like it to compile on a board which lacks Arduino header and doesn't have a default - the app should still be able to compile it and specify manually - presumably the default constructor would not be provided in that case or would error if used due to using "NC".

**Comment by AnttiKauppila** [comment]
These were the only usages I saw.
If you override the values with null, it will compile, but probably won't(?) work.
Whatever target you build, you must have PinName struct defined for the other constructor anyway: 
ESP8266Interface(PinName tx, PinName rx, bool debug = false);
And this mbed_lib.json does not limit to have Arduino pins only, but whatever pins are defined in PinNames.h (or whichever file "PinName" struct is defined for that target board).

**Comment by kjbracey-arm** [comment]
All boards will have `PinName`, but they may not have `D0` and `D1`, so referring to those in the default JSON is problematic. Will generate a compile error even if the driver isn't used.

**Comment by AnttiKauppila** [comment]
Noticed the problem. It is all because mbed compile compiles everything and this would fail even if not used. So I changed default values to NC.

**Pull request merged**
