### PR TITLE
Fix socket state freshness and data availability

### PR DESCRIPTION
**Pull request by marcuschangarm**
When opening TCP and UDP sockets there is a check to see whether
the socket is already in use or not. Because OOB messages are not
handled immediately there might be a mismatch between the stored
state and the actual state. This change processes any outstanding
OOB messages before opening the socket.

Similarly, when receiving data passively there is an internal
variable for keeping track of available data on the wifi modem.
This change processes any outstanding OOB messages before
receiving data.

### CODE REVIEW

**Comment by marcuschangarm** [comment]
Depends on https://github.com/ARMmbed/esp8266-driver/pull/116 and https://github.com/ARMmbed/esp8266-driver/pull/117

**Comment by VeijoPesonen** [comment]
Hmm, seeing here commits which are already part of the master. What might be causing it. Only 
5cf3968 should be visible...

**Comment by VeijoPesonen** [comment]
Replaced with #120  to avoid conflicts...

**Comment by VeijoPesonen** [comment]
I'll close this PR and the same work can be found from PR #120

**Comment by marcuschangarm** [comment]
> Hmm, seeing here commits which are already part of the master. Must be that I have rebased in the middle and this PR is inconsistent state.

That was me. 😄 
I was planning on rebasing once your PR was merged but you beat me to it!

**Comment by VeijoPesonen** [comment]
Working code, better to get it in as soon as possible :)

**Pull request closed without merging**
